# Generated by Django 5.2.3 on 2025-06-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hrs', models.FloatField(help_text='Current Cycle Used (Hrs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('OFF_DUTY', '1. Off Duty (not driving)'), ('SLEEPER_BERTH', '2. Sleeper Berth'), ('DRIVING', '3. Driving'), ('ON_DUTY_NOT_DRIVING', '4. On Duty (not driving)')], default='OFF_DUTY', max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='trips.trip')),
            ],
            options={
                'ordering': ['log_date', 'start_time'],
                'unique_together': {('trip', 'log_date', 'start_time', 'end_time')},
            },
        ),
    ]
