# Generated by Django 5.2.3 on 2025-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='logentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_cycle_used_hrs',
        ),
        migrations.AddField(
            model_name='trip',
            name='current_cycle_used',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('DRIVING', 'Driving'), ('ON_DUTY_NOT_DRIVING', 'On-Duty (Not Driving)'), ('OFF_DUTY', 'Off-Duty'), ('SLEEPER_BERTH', 'Sleeper Berth')], max_length=50),
        ),
    ]
